---
title: "Intergenerational relationships in executive function"
authors: "Johanna Kneidinger, José C. García Alanis"
date:  "`r Sys.Date()`"
output:
html_document:
theme: lumen
highlight: pygments
css: "styler.css"
---

Authors: Johanna Kneidinger & José C. García Alanis

Created with `r R.version.string`

Fit latent models to executive function and delay aversion data.

```{r, setup, include = FALSE}
knitr::opts_chunk$set(class.source = "customCode",
                      class.output = "customOutput",
                      class.message = "customWarning")
if (interactive()) {
  path <- dirname(rstudioapi::getSourceEditorContext()$path)
} else {
  path <- normalizePath('./')
}
setwd(path)
source('utils.R')

require(dplyr)
require(lavaan)
```
```{r load-data}
# load data
data_all <- readRDS(
  file = "data/data_all.rds",
)
```

```{r scale-data}
data_scaled <- data_all %>%
  mutate(across(`MD04_01.1`:`HS01.1`, z_score)) %>%
  mutate(across(`MD04_01.2`:`HS01.2`, z_score))
```

```{r hypothesis-2b}
options(width = 300)
model_h2b <- '
#########################################################
# Measurement model #####################################

# Children ##############################################

DAK1 =~ 1 * MD04_09.1 + MD04_12.1
DAK2 =~ 1 * MD04_09.2 + MD04_12.2

# Parents ###############################################

DAE1 =~ 1 * PB02_09.1 + PB02_12.1
DAE2 =~ 1 * PB02_09.2 + PB02_12.2

# Cross-lagged relationships ############################

DAK2 ~ DAK1
DAK2 ~ DAE1
DAE2 ~ DAE1
DAE2 ~ DAK1

DAK1 ~~ DAE1

########################################################
# Model constraints ####################################

# fix intercepts to zero
MD04_09.1 ~ 0
MD04_12.1 ~ 0
MD04_09.2 ~ 0
MD04_12.2 ~ 0
PB02_09.1 ~ 0
PB02_12.1 ~ 0
PB02_09.2 ~ 0
PB02_12.2 ~ 0

# residual covariances
MD04_09.1 ~~ MD04_09.2
MD04_12.1 ~~ MD04_12.2

PB02_09.1 ~~ PB02_09.2
PB02_12.1 ~~ PB02_12.2
'

# run model
fit_model_h2b <- sem(model = model_h2b, data = data_scaled,
                    estimator = "MLR" , missing = "fiml",
                    std.lv = FALSE)
# get model statistics
summary(fit_model_h2b, fit.measures = TRUE,
        standardized = TRUE, rsquare = TRUE, ci = TRUE)
```

```{r standardised-solution-h2b}
standardizedSolution(fit_model_h2b)
```

```{r mod-indices-h2b}
mi <- modindices(fit_model_h2b)
mi[mi$mi > 20, ] %>% arrange(desc(mi))
```
