---
title: "Intergenerational relationships in executive function"
authors: "Johanna Kneidinger, José C. García Alanis"
date:  "`r Sys.Date()`"
output:
html_document:
theme: lumen
highlight: pygments
css: "styler.css"
---

Authors: Johanna Kneidinger & José C. García Alanis

Created with `r R.version.string`

Fit latent models to executive function and delay aversion data.

```{r, setup, include = FALSE}
knitr::opts_chunk$set(class.source = "customCode",
                      class.output = "customOutput",
                      class.message = "customWarning")
if (interactive()) {
  path <- dirname(rstudioapi::getSourceEditorContext()$path)
} else {
  path <- normalizePath('./')
}
setwd(path)
source('utils.R')

require(dplyr)
require(lavaan)
require(semTools)
```
```{r load-data}
# load data
data_all <- readRDS(
  file = "data/data_all.rds",
)
```

```{r double-mean-centering-data}
data_dmc <- indProd(data = data_all,
                    var1 = c("MD04_01.1", "MD04_02.1", "MD04_04.1", "MD04_07.1",
                             "MD04_03.1", "MD04_05.1", "MD04_06.1", "MD04_08.1",

                             "PB02_01.1", "PB02_02.1", "PB02_04.1", "PB02_07.1",
                             "PB02_03.1", "PB02_05.1", "PB02_06.1", "PB02_08.1"),
                    var2 = c("HS01.1", "HS01.2"),
                    match = FALSE, meanC = TRUE,
                    residualC = FALSE, doubleMC = TRUE)
```

```{r scale-data}
data_scaled <- data_dmc %>%
  mutate(across(`MD04_01.1`:`HS01.1`, z_score)) %>%
  mutate(across(`MD04_01.2`:`HS01.2`, z_score)) %>%
  mutate(across(`MD04_01.1.HS01.1`:`PB02_08.1.HS01.2`))
```


```{r hypothesis-3a}
options(width = 300)
model_h3a <- '
#########################################################
# Measurement model #####################################

# Children ##############################################

AGK1 =~ 1 * MD04_01.1 + MD04_02.1 + MD04_04.1 + MD04_07.1
IHK1 =~ 1 * MD04_03.1 + MD04_05.1 + MD04_06.1 + MD04_08.1

AGK2 =~ 1 * MD04_01.2 + MD04_02.2 + MD04_04.2 + MD04_07.2
IHK2 =~ 1 * MD04_03.2 + MD04_05.2 + MD04_06.2 + MD04_08.2

# Parents ###############################################

AGE1 =~ 1 * PB02_01.1 + PB02_02.1 + PB02_04.1 + PB02_07.1
IHE1 =~ 1 * PB02_03.1 + PB02_05.1 + PB02_06.1 + PB02_08.1

AGE2 =~ 1 * PB02_01.2 + PB02_02.2 + PB02_04.2 + PB02_07.2
IHE2 =~ 1 * PB02_03.2 + PB02_05.2 + PB02_06.2 + PB02_08.2

# Executive functions factors time 1 ####################

EFK1 =~ 1 * AGK1 + 1 * IHK1
EFE1 =~ 1 * AGE1 + 1 * IHE1

# Executive functions factors time 2 ####################

EFK2 =~ 1 * AGK2 + 1 * IHK2
EFE2 =~ 1 * AGE2 + 1 * IHE2

# Moderator #############################################
time_spent =~ 1 * HS01.1 + 1 * HS01.2

# Interaction ###########################################
interaction_k =~ 1 * MD04_01.1.HS01.1 + MD04_01.1.HS01.2 +
                     MD04_02.1.HS01.1 + MD04_02.1.HS01.2 +
                     MD04_04.1.HS01.1 + MD04_04.1.HS01.2 +
                     MD04_07.1.HS01.1 + MD04_07.1.HS01.2 +
                     MD04_03.1.HS01.1 + MD04_03.1.HS01.2 +
                     MD04_05.1.HS01.1 + MD04_05.1.HS01.2 +
                     MD04_06.1.HS01.1 + MD04_06.1.HS01.2 +
                     MD04_08.1.HS01.1 + MD04_08.1.HS01.2

interaction_e =~ 1 * PB02_01.1.HS01.1 + PB02_01.1.HS01.2 +
                     PB02_02.1.HS01.1 + PB02_02.1.HS01.2 +
                     PB02_04.1.HS01.1 + PB02_04.1.HS01.2 +
                     PB02_07.1.HS01.1 + PB02_07.1.HS01.2 +
                     PB02_03.1.HS01.1 + PB02_03.1.HS01.2 +
                     PB02_05.1.HS01.1 + PB02_05.1.HS01.2 +
                     PB02_06.1.HS01.1 + PB02_06.1.HS01.2 +
                     PB02_08.1.HS01.1 + PB02_08.1.HS01.2


# Cross-lagged relationships ############################

EFK2 ~ EFK1
EFK2 ~ EFE1 + time_spent + interaction_e
EFE2 ~ EFE1
EFE2 ~ EFK1 + time_spent + interaction_k

EFK1 ~~ EFE1

########################################################
# Model constraints ####################################

# fix intercepts to zero
MD04_01.1 ~ 0
MD04_02.1 ~ 0
MD04_04.1 ~ 0
MD04_07.1 ~ 0
MD04_03.1 ~ 0
MD04_05.1 ~ 0
MD04_06.1 ~ 0
MD04_08.1 ~ 0

PB02_01.1 ~ 0
PB02_02.1 ~ 0
PB02_04.1 ~ 0
PB02_07.1 ~ 0
PB02_03.1 ~ 0
PB02_05.1 ~ 0
PB02_06.1 ~ 0
PB02_08.1 ~ 0

MD04_01.2 ~ 0
MD04_02.2 ~ 0
MD04_04.2 ~ 0
MD04_07.2 ~ 0
MD04_03.2 ~ 0
MD04_05.2 ~ 0
MD04_06.2 ~ 0
MD04_08.2 ~ 0

PB02_01.2 ~ 0
PB02_02.2 ~ 0
PB02_04.2 ~ 0
PB02_07.2 ~ 0
PB02_03.2 ~ 0
PB02_05.2 ~ 0
PB02_06.2 ~ 0
PB02_08.2 ~ 0

HS01.1 ~ 0
HS01.2 ~ 0

MD04_01.1.HS01.1 ~ 0
MD04_01.1.HS01.2 ~ 0
MD04_02.1.HS01.1 ~ 0
MD04_02.1.HS01.2 ~ 0
MD04_04.1.HS01.1 ~ 0
MD04_04.1.HS01.2 ~ 0
MD04_07.1.HS01.1 ~ 0
MD04_07.1.HS01.2 ~ 0
MD04_03.1.HS01.1 ~ 0
MD04_03.1.HS01.2 ~ 0
MD04_05.1.HS01.1 ~ 0
MD04_05.1.HS01.2 ~ 0
MD04_06.1.HS01.1 ~ 0
MD04_06.1.HS01.2 ~ 0
MD04_08.1.HS01.1 ~ 0
MD04_08.1.HS01.2 ~ 0

PB02_01.1.HS01.1 ~ 0
PB02_01.1.HS01.2 ~ 0
PB02_02.1.HS01.1 ~ 0
PB02_02.1.HS01.2 ~ 0
PB02_04.1.HS01.1 ~ 0
PB02_04.1.HS01.2 ~ 0
PB02_07.1.HS01.1 ~ 0
PB02_07.1.HS01.2 ~ 0
PB02_03.1.HS01.1 ~ 0
PB02_03.1.HS01.2 ~ 0
PB02_05.1.HS01.1 ~ 0
PB02_05.1.HS01.2 ~ 0
PB02_06.1.HS01.1 ~ 0
PB02_06.1.HS01.2 ~ 0
PB02_08.1.HS01.1 ~ 0
PB02_08.1.HS01.2 ~ 0

# Residual covariances

# factor level
EFE2 ~~ 0 * EFE2
EFE2 ~~ 0 * EFK2

# item level
MD04_01.1 ~~ MD04_01.2
MD04_02.1 ~~ MD04_02.2
MD04_04.1 ~~ MD04_04.2
MD04_07.1 ~~ MD04_07.2

MD04_03.1 ~~ MD04_03.2
MD04_05.1 ~~ MD04_05.2
MD04_06.1 ~~ MD04_06.2
MD04_08.1 ~~ MD04_08.2

PB02_01.1 ~~ PB02_01.2
PB02_02.1 ~~ PB02_02.2
PB02_04.1 ~~ PB02_04.2
PB02_07.1 ~~ PB02_07.2

PB02_03.1 ~~ PB02_03.2
PB02_05.1 ~~ PB02_05.2
PB02_06.1 ~~ PB02_06.2
PB02_08.1 ~~ PB02_08.2

MD04_01.1.HS01.1 ~~ MD04_01.1.HS01.2 + MD04_02.1.HS01.1 + MD04_04.1.HS01.1 + MD04_07.1.HS01.1 + MD04_03.1.HS01.1 + MD04_05.1.HS01.1 + MD04_06.1.HS01.1 + MD04_08.1.HS01.1 + PB02_01.1.HS01.1 + PB02_02.1.HS01.1 +  PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 +  PB02_06.1.HS01.1 + PB02_08.1.HS01.1

MD04_01.1.HS01.2 ~~ MD04_02.1.HS01.2 + MD04_04.1.HS01.2 + MD04_07.1.HS01.2 + MD04_03.1.HS01.2 + MD04_05.1.HS01.2 + MD04_06.1.HS01.2 + MD04_08.1.HS01.2 + PB02_01.1.HS01.2 + PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

MD04_02.1.HS01.1 ~~ MD04_02.1.HS01.2 + MD04_04.1.HS01.1 +  MD04_07.1.HS01.1 + MD04_03.1.HS01.1 + MD04_05.1.HS01.1 + MD04_06.1.HS01.1 + MD04_08.1.HS01.1 + PB02_01.1.HS01.1 + PB02_02.1.HS01.1 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

MD04_02.1.HS01.2 ~~ MD04_04.1.HS01.2 + MD04_07.1.HS01.2 + MD04_03.1.HS01.2 + MD04_05.1.HS01.2 + MD04_06.1.HS01.2 + MD04_08.1.HS01.2 + PB02_01.1.HS01.2 + PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

MD04_04.1.HS01.1 ~~ MD04_04.1.HS01.2 + MD04_07.1.HS01.1 + MD04_03.1.HS01.1 + MD04_05.1.HS01.1 + MD04_06.1.HS01.1 + MD04_08.1.HS01.1 + PB02_01.1.HS01.1 + PB02_02.1.HS01.1 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

MD04_04.1.HS01.2 ~~ MD04_07.1.HS01.2 + MD04_03.1.HS01.2 + MD04_05.1.HS01.2 + MD04_06.1.HS01.2 + MD04_08.1.HS01.2 + PB02_01.1.HS01.2 + PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

MD04_07.1.HS01.1 ~~ MD04_07.1.HS01.2 + MD04_03.1.HS01.1 + MD04_05.1.HS01.1 + MD04_06.1.HS01.1 + MD04_08.1.HS01.1 + PB02_01.1.HS01.1 + PB02_02.1.HS01.1 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

MD04_07.1.HS01.2  ~~ MD04_03.1.HS01.2 + MD04_05.1.HS01.2 + MD04_06.1.HS01.2 + MD04_08.1.HS01.2 + PB02_01.1.HS01.2 + PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

MD04_03.1.HS01.1 ~~ MD04_03.1.HS01.2 + MD04_05.1.HS01.1 + MD04_06.1.HS01.1 + MD04_08.1.HS01.1 + PB02_01.1.HS01.1 + PB02_02.1.HS01.1 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

MD04_03.1.HS01.2 ~~ MD04_05.1.HS01.2 + MD04_06.1.HS01.2 + MD04_08.1.HS01.2 + PB02_01.1.HS01.2 + PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

MD04_05.1.HS01.1 ~~ MD04_05.1.HS01.2 + MD04_06.1.HS01.1 + MD04_08.1.HS01.1 + PB02_01.1.HS01.1 + PB02_02.1.HS01.1 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

MD04_05.1.HS01.2 ~~ MD04_06.1.HS01.2 + MD04_08.1.HS01.2 + PB02_01.1.HS01.2 + PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

MD04_06.1.HS01.1 ~~ MD04_06.1.HS01.2 + MD04_08.1.HS01.1 + PB02_01.1.HS01.1 + PB02_02.1.HS01.1 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

MD04_06.1.HS01.2 ~~ MD04_08.1.HS01.2 + PB02_01.1.HS01.2 + PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

MD04_08.1.HS01.1 ~~ MD04_08.1.HS01.2 + PB02_01.1.HS01.1 + PB02_02.1.HS01.1 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

MD04_08.1.HS01.2 ~~ PB02_01.1.HS01.2 + PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

PB02_01.1.HS01.1 ~~ PB02_01.1.HS01.2 + PB02_02.1.HS01.1 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 +  PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

PB02_01.1.HS01.2 ~~ PB02_02.1.HS01.2 + PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 +  PB02_08.1.HS01.2

PB02_02.1.HS01.1 ~~ PB02_02.1.HS01.2 + PB02_04.1.HS01.1 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

PB02_02.1.HS01.2 ~~ PB02_04.1.HS01.2 + PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

PB02_04.1.HS01.1 ~~ PB02_04.1.HS01.2 + PB02_07.1.HS01.1 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

PB02_04.1.HS01.2 ~~ PB02_07.1.HS01.2 + PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

PB02_07.1.HS01.1 ~~ PB02_07.1.HS01.2 + PB02_03.1.HS01.1 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

PB02_07.1.HS01.2 ~~ PB02_03.1.HS01.2 + PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

PB02_03.1.HS01.1 ~~ PB02_03.1.HS01.2 + PB02_05.1.HS01.1 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

PB02_03.1.HS01.2 ~~ PB02_05.1.HS01.2 + PB02_06.1.HS01.2 + PB02_08.1.HS01.2

PB02_05.1.HS01.1 ~~ PB02_05.1.HS01.2 + PB02_06.1.HS01.1 + PB02_08.1.HS01.1

PB02_05.1.HS01.2 ~~ PB02_06.1.HS01.2 + PB02_08.1.HS01.2

PB02_06.1.HS01.1 ~~ PB02_06.1.HS01.2 + PB02_08.1.HS01.1

PB02_06.1.HS01.2 ~~ PB02_08.1.HS01.2

PB02_08.1.HS01.1 ~~ PB02_08.1.HS01.2
'

# run model
fit_model_h3a <- sem(model = model_h3a, data = data_scaled,
                     estimator = "MLR" , missing = "fiml",
                     std.lv = FALSE)
# get model statistics
summary(fit_model_h3a, fit.measures = TRUE,
        standardized = TRUE, rsquare = TRUE, ci = TRUE)
```

```{r standardised-solution-h3a}
standardizedSolution(fit_model_h3a)
```

```{r mod-indices-h3a}
mi <- modindices(fit_model_h3a)
mi[mi$mi > 20, ] %>% arrange(desc(mi))
```