---
title: "Intergenerational relationships in executive function"
authors: "Johanna Kneidinger, José C. García Alanis"
date:  "`r Sys.Date()`"
output:
html_document:
theme: lumen
highlight: pygments
css: "styler.css"
---

Authors: Johanna Kneidinger & José C. García Alanis

Created with `r R.version.string`

Fit latent models to executive function and delay aversion data.

```{r, setup, include = FALSE}
knitr::opts_chunk$set(class.source = "customCode",
                      class.output = "customOutput",
                      class.message = "customWarning")
if (interactive()) {
  path <- dirname(rstudioapi::getSourceEditorContext()$path)
} else {
  path <- normalizePath('./')
}
setwd(path)
source('utils.R')

require(dplyr)
require(lavaan)
require(semTools)
```
```{r load-data}
# load data
data_all <- readRDS(
  file = "data/data_all.rds",
)
```

```{r double-mean-centering-data}
data_dmc <- indProd(data = data_all,
                    var1 = c("MD04_09.1", "MD04_12.1",
                             "PB02_09.1", "PB02_12.1"),
                    var2 = c("HS01.1", "HS01.2"),
                    match = FALSE, meanC = TRUE,
                    residualC = FALSE, doubleMC = TRUE)
```

```{r scale-data}
data_scaled <- data_dmc %>%
        mutate(across(`MD04_01.1`:`HS01.1`, z_score)) %>%
        mutate(across(`MD04_01.2`:`HS01.2`, z_score)) %>%
        mutate(across(`MD04_09.1.HS01.1`:`PB02_12.1.HS01.2`))
```

```{r hypothesis-3b}
options(width = 300)
model_h3b <- '
#########################################################
# Measurement model #####################################

# Children ##############################################

DAK1 =~ 1 * MD04_09.1 + MD04_12.1
DAK2 =~ 1 * MD04_09.2 + MD04_12.2

# Parents ###############################################

DAE1 =~ 1 * PB02_09.1 + PB02_12.1
DAE2 =~ 1 * PB02_09.2 + PB02_12.2

# Moderator #############################################
time_spent =~ 1 * HS01.1 + 1 * HS01.2

# Interaction ###########################################
interaction_k =~ 1 * MD04_09.1.HS01.1 + MD04_09.1.HS01.2 +
                     MD04_12.1.HS01.1 + MD04_12.1.HS01.2
interaction_e =~ 1 * PB02_09.1.HS01.1 + PB02_09.1.HS01.2 +
                     PB02_12.1.HS01.1 + PB02_12.1.HS01.2

# Cross-lagged relationships ############################

DAK2 ~ DAK1
DAK2 ~ DAE1 + time_spent + interaction_e
DAE2 ~ DAE1
DAE2 ~ DAK1 + time_spent + interaction_k

DAK1 ~~ DAE1

########################################################
# Model constraints ####################################

# fix intercepts to zero
MD04_09.1 ~ 0
MD04_12.1 ~ 0

PB02_09.1 ~ 0
PB02_12.1 ~ 0

MD04_09.2 ~ 0
MD04_12.2 ~ 0

PB02_09.2 ~ 0
PB02_12.2 ~ 0

HS01.1 ~ 0
HS01.2 ~ 0

MD04_09.1.HS01.1 ~ 0
MD04_09.1.HS01.2 ~ 0

MD04_12.1.HS01.1 ~ 0
MD04_12.1.HS01.2 ~ 0

PB02_09.1.HS01.1 ~ 0
PB02_09.1.HS01.2 ~ 0

PB02_12.1.HS01.1 ~ 0
PB02_12.1.HS01.2 ~ 0

# residual covariances
MD04_09.1 ~~ MD04_09.2
MD04_12.1 ~~ MD04_12.2

PB02_09.1 ~~ PB02_09.2
PB02_12.1 ~~ PB02_12.2

MD04_09.1.HS01.1 ~~ MD04_09.1.HS01.2 + MD04_12.1.HS01.1 + PB02_09.1.HS01.1 + PB02_12.1.HS01.1
MD04_09.1.HS01.2 ~~ MD04_12.1.HS01.2 + PB02_09.1.HS01.2 + PB02_12.1.HS01.2
MD04_12.1.HS01.1 ~~ MD04_12.1.HS01.2 + PB02_09.1.HS01.1 + PB02_12.1.HS01.1
MD04_12.1.HS01.2 ~~ PB02_09.1.HS01.2 + PB02_12.1.HS01.2
PB02_09.1.HS01.1 ~~ PB02_09.1.HS01.2 + PB02_12.1.HS01.1
PB02_09.1.HS01.2 ~~ PB02_12.1.HS01.2
PB02_12.1.HS01.1 ~~ PB02_12.1.HS01.2
'

# run model
fit_model_h3b <- sem(model = model_h3b, data = data_scaled,
                     estimator = "MLR" , missing = "fiml",
                     std.lv = FALSE)
# get model statistics
summary(fit_model_h3b, fit.measures = TRUE,
        standardized = TRUE, rsquare = TRUE, ci = TRUE)
```

```{r mod-indices-h3b}
mi <- modindices(fit_model_h3b)
mi[mi$mi > 20, ] %>% arrange(desc(mi))
```
